### ISSUE TITLE
Explicit add_cap MKNOD is not necessary for docker, but ...

### ISSUE THREAD

**Issue by jnweiger** [ValentinKruegl/owncloud_collabora#1]
https://github.com/CollaboraOnline/online/blob/master/common/JailUtil.cpp#L330

With recent docker, it seems, that the mknod() call succeeds, even if the MKNOD capability is not explicitly granted.
We see a debug log message "Created random device" in the collabora log file.
If mknod would fail, we should see instead a warning "Performance issue: nodev mount permission or mknod fails. Have to bind mount "

According to https://github.com/moby/moby/blob/master/oci/caps/defaults.go
docker has CAP_MKNOD always enabled as a default capability.

Conclusion:
* add_cap MKNOD is unnecessary here.
* In general, it might be still be safer to explicitly specify the capability, as we don't know how future docker or podman or kybernetes have their defaults.
* There is no security impact with or without the flag.

**Comment by ValentinKruegl** [comment]
Thanks, changed the docker compose to remove mknod
